export SERVE_PUBLIC_BASE_URL=${AUTHN_PUBLIC_URL}
export DSN=${AUTHN_DB_URL}

export SELFSERVICE_FLOWS_LOGIN_UI_URL=${AUTHN_UI_URL}/login
export SELFSERVICE_FLOWS_LOGIN_LIFESPAN="2m"

export SELFSERVICE_FLOWS_SETTINGS_UI_URL=${AUTHN_UI_URL}/settings
export SELFSERVICE_FLOWS_ERROR_UI_URL=${AUTHN_UI_URL}/error
export SELFSERVICE_FLOWS_RECOVERY_UI_URL=${AUTHN_UI_URL}/recovery
export SELFSERVICE_FLOWS_VERIFICATION_UI_URL=${AUTHN_UI_URL}/verification
export SELFSERVICE_FLOWS_REGISTRATION_UI_URL=${AUTHN_UI_URL}/registration
export SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=${AUTHN_UI_URL}
export VERSION=${KRATOS_VERSION}